# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

# development:
#   <<: *default
#   database: ENV["dev_db"]
#   username: ENV["dev_un"]
#   password: ENV["dev_pw"]

development:
  <<: *default
  host: localhost
  username: user
  database: app-dev

test:
  <<: *default
  database: ENV["test_db"]
  username: ENV["test_un"]
  password: ENV["test_pw"]

production:
  <<: *default
  database: ENV["prod_db"]
  username: ENV["prod_un"]
  password: ENV["prod_pw"]
