# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e97f5e29eabb6b733ffe3197f480bf61aa417af7bdd8c58553384f7b07d8658ee5248d95186b1aceb3fdba18e2e49bed44ba5fb037cc83a0e801c23fa53e82e2
  publishable_key: pk_test_bbWycAxBBkc7Jo9kejH7BpOL
  secret_key: sk_test_TfFdb0OJFgxF6PAzQiIxPF7q

test:
  secret_key_base: bbad8e8b71a3a42247aacebf901db67c231bc69006871be3cdc6117874813a0baf3c934214b8f6669a68e219b18dbf5b06a4d4e488056b5d0d27ea0bc1472f18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
